# Generated by Django 4.2.2 on 2023-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SneakerApp', '0002_customer_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='North Macedonia', max_length=255),
            preserve_default=False,
        ),
    ]
