# Generated by Django 4.2.2 on 2023-06-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SneakerApp', '0003_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shoe_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
